import type { PrismaClient } from '../app/generated/prisma/client'

type ExerciseInput = {
  id: string
  name: string
  type: 'PUSH' | 'PULL' | 'LEGS' | 'ABS' | 'FULL_BODY' | 'CARDIO' | 'STRETCHING'
  muscleGroup: string
  sets: number
  reps: string
  level: 'DEBUTANT' | 'INTERMEDIAIRE' | 'AVANCE'
  equipment: string
  description: string
  exerciseDbId?: string
}

export const EXERCISES: ExerciseInput[] = [
  // ─── PUSH (10) ───────────────────────────────────────────────────────────────
  {
    id: 'ex-push-01',
    name: 'Développé couché',
    type: 'PUSH',
    muscleGroup: 'Poitrine',
    sets: 3,
    reps: '8-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Barre',
    description: 'Allongé sur un banc, descends la barre jusqu\'à la poitrine puis pousse vers le haut en contractant les pectoraux.',
    exerciseDbId: '0017',
  },
  {
    id: 'ex-push-02',
    name: 'Développé incliné',
    type: 'PUSH',
    muscleGroup: 'Poitrine haute',
    sets: 3,
    reps: '8-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Barre',
    description: 'Sur banc incliné à 30-45°, cible le haut des pectoraux. Même mouvement que le développé couché.',
  },
  {
    id: 'ex-push-03',
    name: 'Développé militaire',
    type: 'PUSH',
    muscleGroup: 'Épaules',
    sets: 3,
    reps: '8-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Barre',
    description: 'Debout ou assis, pousse la barre au-dessus de la tête depuis les épaules. Contracte les deltoïdes en haut.',
    exerciseDbId: '0054',
  },
  {
    id: 'ex-push-04',
    name: 'Dips',
    type: 'PUSH',
    muscleGroup: 'Triceps',
    sets: 3,
    reps: '8-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Barres parallèles',
    description: 'Suspension sur barres parallèles, descends jusqu\'à 90° de flexion au coude puis pousse vers le haut.',
  },
  {
    id: 'ex-push-05',
    name: 'Élévations latérales',
    type: 'PUSH',
    muscleGroup: 'Épaules',
    sets: 3,
    reps: '12-15',
    level: 'DEBUTANT',
    equipment: 'Haltères',
    description: 'Debout, lève les haltères sur les côtés jusqu\'à hauteur des épaules avec les coudes légèrement fléchis.',
  },
  {
    id: 'ex-push-06',
    name: 'Élévations frontales',
    type: 'PUSH',
    muscleGroup: 'Épaules',
    sets: 3,
    reps: '12-15',
    level: 'DEBUTANT',
    equipment: 'Haltères',
    description: 'Lève les haltères devant toi jusqu\'à hauteur des épaules. Cible le faisceau antérieur du deltoïde.',
  },
  {
    id: 'ex-push-07',
    name: 'Écartés haltères',
    type: 'PUSH',
    muscleGroup: 'Poitrine',
    sets: 3,
    reps: '12-15',
    level: 'DEBUTANT',
    equipment: 'Haltères',
    description: 'Sur banc horizontal, descends les haltères en arc de cercle sur les côtés puis remonte. Étire et contracte les pectoraux.',
  },
  {
    id: 'ex-push-08',
    name: 'Triceps poulie',
    type: 'PUSH',
    muscleGroup: 'Triceps',
    sets: 3,
    reps: '12-15',
    level: 'DEBUTANT',
    equipment: 'Poulie',
    description: 'Debout face à la poulie haute, coudes fixes contre le corps, pousse la corde vers le bas en contractant les triceps.',
  },
  {
    id: 'ex-push-09',
    name: 'Triceps barre',
    type: 'PUSH',
    muscleGroup: 'Triceps',
    sets: 3,
    reps: '10-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Barre',
    description: 'Allongé sur banc, barre tenue à largeur d\'épaules, fléchis les coudes pour amener la barre vers le front puis étends.',
  },
  {
    id: 'ex-push-10',
    name: 'Pushups',
    type: 'PUSH',
    muscleGroup: 'Poitrine',
    sets: 3,
    reps: '15-20',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Au sol, mains à largeur d\'épaules, corps droit. Descends la poitrine jusqu\'au sol puis pousse en contractant les pectoraux.',
    exerciseDbId: '0022',
  },

  // ─── PULL (10) ───────────────────────────────────────────────────────────────
  {
    id: 'ex-pull-01',
    name: 'Tractions',
    type: 'PULL',
    muscleGroup: 'Dos',
    sets: 3,
    reps: '6-10',
    level: 'AVANCE',
    equipment: 'Barre de traction',
    description: 'Suspendu à une barre, tire ton corps vers le haut jusqu\'à ce que le menton dépasse la barre. Contracte le grand dorsal.',
    exerciseDbId: '0031',
  },
  {
    id: 'ex-pull-02',
    name: 'Rowing barre',
    type: 'PULL',
    muscleGroup: 'Dos',
    sets: 3,
    reps: '8-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Barre',
    description: 'Buste incliné à 45°, tire la barre vers le bas du ventre en gardant le dos plat. Contracte les dorsaux et les rhomboïdes.',
    exerciseDbId: '0084',
  },
  {
    id: 'ex-pull-03',
    name: 'Rowing haltères',
    type: 'PULL',
    muscleGroup: 'Dos',
    sets: 3,
    reps: '10-12',
    level: 'DEBUTANT',
    equipment: 'Haltères',
    description: 'Un genou sur un banc pour support, tire l\'haltère vers la hanche en gardant le coude proche du corps.',
  },
  {
    id: 'ex-pull-04',
    name: 'Curl biceps barre',
    type: 'PULL',
    muscleGroup: 'Biceps',
    sets: 3,
    reps: '10-12',
    level: 'DEBUTANT',
    equipment: 'Barre',
    description: 'Debout, coudes fixes contre le corps, fléchis les avant-bras pour amener la barre vers les épaules. Contracte les biceps.',
  },
  {
    id: 'ex-pull-05',
    name: 'Curl haltères',
    type: 'PULL',
    muscleGroup: 'Biceps',
    sets: 3,
    reps: '10-12',
    level: 'DEBUTANT',
    equipment: 'Haltères',
    description: 'Alternativement ou simultanément, fléchis les avant-bras pour amener les haltères vers les épaules.',
    exerciseDbId: '0059',
  },
  {
    id: 'ex-pull-06',
    name: 'Curl marteau',
    type: 'PULL',
    muscleGroup: 'Biceps',
    sets: 3,
    reps: '10-12',
    level: 'DEBUTANT',
    equipment: 'Haltères',
    description: 'Comme le curl haltères mais prise neutre (pouce vers le haut). Cible le long biceps et le brachio-radial.',
  },
  {
    id: 'ex-pull-07',
    name: 'Tirage poulie haute',
    type: 'PULL',
    muscleGroup: 'Dos',
    sets: 3,
    reps: '10-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Poulie',
    description: 'Assis face à la poulie haute, tire la barre vers le haut de la poitrine en écartant les coudes sur les côtés.',
  },
  {
    id: 'ex-pull-08',
    name: 'Face pull',
    type: 'PULL',
    muscleGroup: 'Épaules',
    sets: 3,
    reps: '15-20',
    level: 'DEBUTANT',
    equipment: 'Poulie',
    description: 'Face à la poulie haute, tire la corde vers le visage en écartant les coudes. Cible les deltoïdes postérieurs.',
  },
  {
    id: 'ex-pull-09',
    name: 'Shrugs',
    type: 'PULL',
    muscleGroup: 'Trapèzes',
    sets: 3,
    reps: '12-15',
    level: 'DEBUTANT',
    equipment: 'Haltères',
    description: 'Debout, haltères le long du corps, hausse les épaules le plus haut possible. Contracte les trapèzes en haut.',
  },
  {
    id: 'ex-pull-10',
    name: 'Deadlift roumain',
    type: 'PULL',
    muscleGroup: 'Ischio-jambiers',
    sets: 3,
    reps: '10-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Barre',
    description: 'Barre en main, descends en gardant les jambes quasi-tendues jusqu\'à sentir l\'étirement des ischio-jambiers, puis remonte.',
  },

  // ─── LEGS (10) ───────────────────────────────────────────────────────────────
  {
    id: 'ex-legs-01',
    name: 'Squat barre',
    type: 'LEGS',
    muscleGroup: 'Quadriceps',
    sets: 3,
    reps: '8-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Barre',
    description: 'Barre sur les trapèzes, descends jusqu\'aux cuisses parallèles au sol puis remonte. Le roi des exercices pour les jambes.',
    exerciseDbId: '0043',
  },
  {
    id: 'ex-legs-02',
    name: 'Presse à cuisses',
    type: 'LEGS',
    muscleGroup: 'Quadriceps',
    sets: 3,
    reps: '10-12',
    level: 'DEBUTANT',
    equipment: 'Machine',
    description: 'Sur la machine presse, pousse les plateaux jusqu\'à quasi-extension des jambes. Pieds à largeur de hanches.',
    exerciseDbId: '0119',
  },
  {
    id: 'ex-legs-03',
    name: 'Fentes avant',
    type: 'LEGS',
    muscleGroup: 'Quadriceps',
    sets: 3,
    reps: '10-12',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Fais un grand pas en avant, descends le genou arrière vers le sol puis remonte. Garde le buste droit.',
  },
  {
    id: 'ex-legs-04',
    name: 'Fentes bulgares',
    type: 'LEGS',
    muscleGroup: 'Quadriceps',
    sets: 3,
    reps: '8-10',
    level: 'INTERMEDIAIRE',
    equipment: 'Haltères',
    description: 'Pied arrière posé sur un banc, descends le genou avant jusqu\'au sol. Excellent pour l\'équilibre et le fessier.',
  },
  {
    id: 'ex-legs-05',
    name: 'Leg curl',
    type: 'LEGS',
    muscleGroup: 'Ischio-jambiers',
    sets: 3,
    reps: '12-15',
    level: 'DEBUTANT',
    equipment: 'Machine',
    description: 'Allongé sur la machine leg curl, fléchis les jambes pour amener les talons vers les fessiers. Contracte en haut.',
  },
  {
    id: 'ex-legs-06',
    name: 'Leg extension',
    type: 'LEGS',
    muscleGroup: 'Quadriceps',
    sets: 3,
    reps: '12-15',
    level: 'DEBUTANT',
    equipment: 'Machine',
    description: 'Assis sur la machine, étends les jambes jusqu\'à quasi-extension. Isole parfaitement les quadriceps.',
  },
  {
    id: 'ex-legs-07',
    name: 'Mollets debout',
    type: 'LEGS',
    muscleGroup: 'Mollets',
    sets: 3,
    reps: '15-20',
    level: 'DEBUTANT',
    equipment: 'Haltères',
    description: 'Debout sur une marche, monte sur les pointes de pieds le plus haut possible puis redescends lentement.',
  },
  {
    id: 'ex-legs-08',
    name: 'Mollets assis',
    type: 'LEGS',
    muscleGroup: 'Mollets',
    sets: 3,
    reps: '15-20',
    level: 'DEBUTANT',
    equipment: 'Machine',
    description: 'Assis sur la machine mollets, cible le soléaire (le mollet profond). Monte sur pointes de pieds, descends lentement.',
  },
  {
    id: 'ex-legs-09',
    name: 'Hip thrust',
    type: 'LEGS',
    muscleGroup: 'Fessiers',
    sets: 3,
    reps: '12-15',
    level: 'INTERMEDIAIRE',
    equipment: 'Barre',
    description: 'Dos appuyé sur un banc, barre sur les hanches, pousse les hanches vers le haut jusqu\'à extension complète. Contracte les fessiers.',
  },
  {
    id: 'ex-legs-10',
    name: 'Goblet squat',
    type: 'LEGS',
    muscleGroup: 'Quadriceps',
    sets: 3,
    reps: '12-15',
    level: 'DEBUTANT',
    equipment: 'Haltères',
    description: 'Tiens un haltère contre la poitrine, descends en squat profond. Excellent pour la technique et la mobilité.',
  },

  // ─── ABS (8) ─────────────────────────────────────────────────────────────────
  {
    id: 'ex-abs-01',
    name: 'Crunchs',
    type: 'ABS',
    muscleGroup: 'Abdominaux',
    sets: 3,
    reps: '20',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Allongé sur le dos, mains derrière la tête, monte les épaules vers les genoux. Contracte les abdominaux à chaque répétition.',
  },
  {
    id: 'ex-abs-02',
    name: 'Planche',
    type: 'ABS',
    muscleGroup: 'Abdominaux',
    sets: 3,
    reps: '30 sec',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'En appui sur les avant-bras et les orteils, garde le corps parfaitement droit. Contracte le ventre et les fessiers.',
  },
  {
    id: 'ex-abs-03',
    name: 'Relevés de jambes',
    type: 'ABS',
    muscleGroup: 'Abdominaux bas',
    sets: 3,
    reps: '15-20',
    level: 'INTERMEDIAIRE',
    equipment: 'Aucun',
    description: 'Allongé sur le dos, lève les jambes tendues jusqu\'à la verticale puis redescends lentement sans toucher le sol.',
  },
  {
    id: 'ex-abs-04',
    name: 'Russian twist',
    type: 'ABS',
    muscleGroup: 'Obliques',
    sets: 3,
    reps: '20',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Assis, jambes levées et fléchies, fais des rotations du buste de gauche à droite. Option : tenir un haltère.',
  },
  {
    id: 'ex-abs-05',
    name: 'Bicycle crunch',
    type: 'ABS',
    muscleGroup: 'Obliques',
    sets: 3,
    reps: '20',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Allongé sur le dos, amène le coude gauche vers le genou droit et vice-versa en pédalant avec les jambes.',
  },
  {
    id: 'ex-abs-06',
    name: 'Ab wheel',
    type: 'ABS',
    muscleGroup: 'Abdominaux',
    sets: 3,
    reps: '10-15',
    level: 'AVANCE',
    equipment: 'Roue abdominale',
    description: 'À genoux, roule la roue vers l\'avant en gardant les bras tendus puis reviens en contractant les abdominaux.',
  },
  {
    id: 'ex-abs-07',
    name: 'Dragon flag',
    type: 'ABS',
    muscleGroup: 'Abdominaux',
    sets: 3,
    reps: '8-10',
    level: 'AVANCE',
    equipment: 'Banc',
    description: 'Allongé sur banc, mains derrière la tête agrippées, soulève tout le corps en position rigide puis redescends lentement.',
  },
  {
    id: 'ex-abs-08',
    name: 'Hollow hold',
    type: 'ABS',
    muscleGroup: 'Abdominaux',
    sets: 3,
    reps: '30 sec',
    level: 'INTERMEDIAIRE',
    equipment: 'Aucun',
    description: 'Allongé sur le dos, contracte fort les abdominaux pour creuser le bas du dos et soulever jambes et épaules.',
  },

  // ─── FULL_BODY (10) ──────────────────────────────────────────────────────────
  {
    id: 'ex-fb-01',
    name: 'Deadlift',
    type: 'FULL_BODY',
    muscleGroup: 'Dos / Quadriceps',
    sets: 3,
    reps: '5-8',
    level: 'AVANCE',
    equipment: 'Barre',
    description: 'Barre au sol, pieds à largeur de hanches, soulève la barre en gardant le dos plat jusqu\'à la position debout.',
    exerciseDbId: '0233',
  },
  {
    id: 'ex-fb-02',
    name: 'Clean',
    type: 'FULL_BODY',
    muscleGroup: 'Corps entier',
    sets: 3,
    reps: '5-8',
    level: 'AVANCE',
    equipment: 'Barre',
    description: 'Mouvement olympique : soulève la barre depuis le sol jusqu\'aux épaules en une extension explosive des chevilles, genoux et hanches.',
  },
  {
    id: 'ex-fb-03',
    name: 'Burpees',
    type: 'FULL_BODY',
    muscleGroup: 'Corps entier',
    sets: 3,
    reps: '15-20',
    level: 'INTERMEDIAIRE',
    equipment: 'Aucun',
    description: 'Depuis debout, pose les mains au sol, recule en planche, fais une pompe, reviens aux mains puis saute avec les bras en l\'air.',
  },
  {
    id: 'ex-fb-04',
    name: 'Kettlebell swing',
    type: 'FULL_BODY',
    muscleGroup: 'Corps entier',
    sets: 3,
    reps: '15-20',
    level: 'INTERMEDIAIRE',
    equipment: 'Kettlebell',
    description: 'Bascule le kettlebell entre tes jambes puis propulse-le à hauteur des épaules par une extension explosive des hanches.',
  },
  {
    id: 'ex-fb-05',
    name: 'Thruster',
    type: 'FULL_BODY',
    muscleGroup: 'Corps entier',
    sets: 3,
    reps: '10-12',
    level: 'AVANCE',
    equipment: 'Barre',
    description: 'Enchaîne un squat barre et un développé militaire en un seul mouvement fluide. Exercice total corps très intense.',
  },
  {
    id: 'ex-fb-06',
    name: 'Box jump',
    type: 'FULL_BODY',
    muscleGroup: 'Quadriceps / Fessiers',
    sets: 3,
    reps: '10-12',
    level: 'INTERMEDIAIRE',
    equipment: 'Box',
    description: 'Saute sur une boîte depuis une position accroupie avec les bras en balancier. Descends et recommence.',
  },
  {
    id: 'ex-fb-07',
    name: 'Man maker',
    type: 'FULL_BODY',
    muscleGroup: 'Corps entier',
    sets: 3,
    reps: '8-10',
    level: 'AVANCE',
    equipment: 'Haltères',
    description: 'Haltères au sol : pompe, rowing gauche, rowing droit, squat, développé épaules. Enchaîne les 5 mouvements sans pause.',
  },
  {
    id: 'ex-fb-08',
    name: 'Turkish get-up',
    type: 'FULL_BODY',
    muscleGroup: 'Corps entier',
    sets: 3,
    reps: '5 rép chaque côté',
    level: 'AVANCE',
    equipment: 'Kettlebell',
    description: 'Allongé sur le dos, bras tendu avec le kettlebell, lève-toi debout en maintenant le kettlebell en l\'air. Mouvement complexe de stabilité.',
  },
  {
    id: 'ex-fb-09',
    name: 'Snatch haltère',
    type: 'FULL_BODY',
    muscleGroup: 'Corps entier',
    sets: 3,
    reps: '5-8',
    level: 'AVANCE',
    equipment: 'Haltères',
    description: 'En une seule traction explosive, amène l\'haltère du sol au-dessus de la tête en bras tendu. Développe la puissance.',
  },
  {
    id: 'ex-fb-10',
    name: 'Bear crawl',
    type: 'FULL_BODY',
    muscleGroup: 'Corps entier',
    sets: 3,
    reps: '20m',
    level: 'INTERMEDIAIRE',
    equipment: 'Aucun',
    description: 'À 4 pattes avec les genoux décollés du sol (10 cm), avance en déplaçant bras et jambe opposés. Maintiens le dos plat.',
  },

  // ─── CARDIO (10) ─────────────────────────────────────────────────────────────
  {
    id: 'ex-cardio-01',
    name: 'Course à pied',
    type: 'CARDIO',
    muscleGroup: 'Cardio',
    sets: 1,
    reps: '30 min',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Course à allure modérée, idéalement à l\'extérieur. Maintiens une fréquence cardiaque entre 65-75% de ta FC max.',
  },
  {
    id: 'ex-cardio-02',
    name: 'Vélo stationnaire',
    type: 'CARDIO',
    muscleGroup: 'Cardio',
    sets: 1,
    reps: '30 min',
    level: 'DEBUTANT',
    equipment: 'Vélo',
    description: 'Pédale à intensité modérée. Ajuste la résistance pour maintenir un effort constant. Doux pour les articulations.',
  },
  {
    id: 'ex-cardio-03',
    name: 'Corde à sauter',
    type: 'CARDIO',
    muscleGroup: 'Cardio',
    sets: 3,
    reps: '3 min',
    level: 'INTERMEDIAIRE',
    equipment: 'Corde',
    description: 'Saute à la corde à rythme régulier. Excellent pour la coordination et l\'endurance cardio-respiratoire.',
  },
  {
    id: 'ex-cardio-04',
    name: 'Rameur',
    type: 'CARDIO',
    muscleGroup: 'Cardio',
    sets: 1,
    reps: '20 min',
    level: 'INTERMEDIAIRE',
    equipment: 'Rameur',
    description: 'Rame en alternant phases de poussée (jambes) et de traction (bras). Complet : 60% jambes, 30% dos, 10% bras.',
  },
  {
    id: 'ex-cardio-05',
    name: 'HIIT tabata',
    type: 'CARDIO',
    muscleGroup: 'Cardio',
    sets: 8,
    reps: '20 sec effort / 10 sec repos',
    level: 'INTERMEDIAIRE',
    equipment: 'Aucun',
    description: '8 cycles de 20 sec d\'effort maximal (ex: squats sautés) suivi de 10 sec de repos. 4 min total, impact métabolique élevé.',
  },
  {
    id: 'ex-cardio-06',
    name: 'Jumping jacks',
    type: 'CARDIO',
    muscleGroup: 'Cardio',
    sets: 3,
    reps: '50 rép',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Sauts en écartant les jambes et en levant les bras. Exercice cardio d\'échauffement ou de récupération active.',
  },
  {
    id: 'ex-cardio-07',
    name: 'Mountain climbers',
    type: 'CARDIO',
    muscleGroup: 'Cardio',
    sets: 3,
    reps: '30 sec',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'En position de planche, ramène alternativement les genoux vers la poitrine le plus vite possible. Brûle les calories.',
  },
  {
    id: 'ex-cardio-08',
    name: 'Sprint 30s',
    type: 'CARDIO',
    muscleGroup: 'Cardio',
    sets: 6,
    reps: '30 sec sprint / 90 sec récup',
    level: 'INTERMEDIAIRE',
    equipment: 'Aucun',
    description: 'Sprint à intensité maximale pendant 30 sec, récupère 90 sec en marchant. Excellente stimulation hormonale.',
  },
  {
    id: 'ex-cardio-09',
    name: 'Natation',
    type: 'CARDIO',
    muscleGroup: 'Corps entier',
    sets: 1,
    reps: '30 min',
    level: 'DEBUTANT',
    equipment: 'Piscine',
    description: 'Nage libre ou crawl à allure modérée. Complet et doux pour les articulations, excellent pour la récupération active.',
  },
  {
    id: 'ex-cardio-10',
    name: 'Elliptique',
    type: 'CARDIO',
    muscleGroup: 'Corps entier',
    sets: 1,
    reps: '30 min',
    level: 'DEBUTANT',
    equipment: 'Elliptique',
    description: 'Entraînement elliptique à intensité modérée. Combine le mouvement des bras et des jambes sans impact sur les articulations.',
  },

  // ─── STRETCHING (10) ─────────────────────────────────────────────────────────
  {
    id: 'ex-str-01',
    name: 'Hip flexor stretch',
    type: 'STRETCHING',
    muscleGroup: 'Fléchisseurs de hanche',
    sets: 2,
    reps: '30 sec',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'En fente basse, genou arrière au sol, pousse les hanches en avant pour étirer le psoas. Idéal après une longue période assis.',
  },
  {
    id: 'ex-str-02',
    name: 'Pigeon pose',
    type: 'STRETCHING',
    muscleGroup: 'Fessiers',
    sets: 2,
    reps: '60 sec',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Depuis la planche, amène un genou vers le poignet et étends la jambe arrière. Penche le buste en avant pour accentuer.',
  },
  {
    id: 'ex-str-03',
    name: 'Cat-cow',
    type: 'STRETCHING',
    muscleGroup: 'Dos',
    sets: 2,
    reps: '10 rép',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'À 4 pattes, alterne entre dos voûté (cat) et dos creusé (cow) en synchronisant avec ta respiration.',
  },
  {
    id: 'ex-str-04',
    name: 'Downward dog',
    type: 'STRETCHING',
    muscleGroup: 'Corps entier',
    sets: 2,
    reps: '30 sec',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Depuis la planche, lève les hanches pour former un V inversé. Étire les ischio-jambiers, mollets et épaules simultanément.',
  },
  {
    id: 'ex-str-05',
    name: 'Shoulder cross stretch',
    type: 'STRETCHING',
    muscleGroup: 'Épaules',
    sets: 2,
    reps: '30 sec',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Ramène un bras tendu devant toi à hauteur des épaules et maintiens-le avec l\'autre bras. Étire le deltoïde postérieur.',
  },
  {
    id: 'ex-str-06',
    name: 'Hamstring stretch',
    type: 'STRETCHING',
    muscleGroup: 'Ischio-jambiers',
    sets: 2,
    reps: '30 sec',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Assis sur le sol, jambes tendues, penche le buste vers l\'avant pour toucher les orteils. Garde le dos droit.',
  },
  {
    id: 'ex-str-07',
    name: 'Quad stretch',
    type: 'STRETCHING',
    muscleGroup: 'Quadriceps',
    sets: 2,
    reps: '30 sec',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Debout, fléchis un genou et attrape le pied derrière toi. Pousse la hanche en avant pour accentuer l\'étirement.',
  },
  {
    id: 'ex-str-08',
    name: 'Thoracic rotation',
    type: 'STRETCHING',
    muscleGroup: 'Dos',
    sets: 2,
    reps: '10 rép',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'En position latérale, genoux fléchis, ouvre le bras supérieur vers l\'arrière pour faire tourner le thorax. Améliore la mobilité.',
  },
  {
    id: 'ex-str-09',
    name: 'Neck rolls',
    type: 'STRETCHING',
    muscleGroup: 'Cou',
    sets: 2,
    reps: '10 rép',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'Doucement, incline la tête sur les côtés, vers l\'avant et vers l\'arrière. Ne fais pas de rotations complètes rapides.',
  },
  {
    id: 'ex-str-10',
    name: "Child's pose",
    type: 'STRETCHING',
    muscleGroup: 'Dos',
    sets: 2,
    reps: '60 sec',
    level: 'DEBUTANT',
    equipment: 'Aucun',
    description: 'À genoux, assieds-toi sur les talons et étends les bras devant toi au sol. Étirement doux et récupérateur pour le bas du dos.',
  },
]

export async function seedExercises(prisma: PrismaClient) {
  console.log('Seeding exercises catalogue...')
  let count = 0
  for (const ex of EXERCISES) {
    await prisma.exercise.upsert({
      where: { id: ex.id },
      create: ex,
      update: {
        name: ex.name,
        type: ex.type,
        muscleGroup: ex.muscleGroup,
        sets: ex.sets,
        reps: ex.reps,
        level: ex.level,
        equipment: ex.equipment,
        description: ex.description,
        exerciseDbId: ex.exerciseDbId ?? null,
      },
    })
    count++
  }
  console.log(`  ✓ ${count} exercises seeded`)
}
